spring:
  application:
    name: monolith
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/corebank
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password: ""
